
services:
  # PostgreSQL Database
  postgres:
    container_name: lambda-postgres-ctr
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB : ${POSTGRES_DB}
    ports:
      - "5432:5432"
    mem_limit: 2g
    cpus: 1.0
    volumes:
      - fraud-detection-postgres:/var/lib/postgresql/batch-datasource
    networks:
      - finance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataeng"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Pgadmin
  pgadmin:
    container_name: lambda-pgadmin-ctr
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    mem_limit: 512m
    cpus: .25
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - finance-network

  airflow:
    image: apache/airflow:2.9.3-python3.11
    container_name: lambda-airflow-ctr
    env_file:
      .env
    user: "50000:984"
    environment:
      AIRFLOW__SMTP__SMTP_HOST: smtp.protonmail.ch
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_USER: ${PROTON_EMAIL}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${PROTON_SMTP_TOKEN}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${PROTON_EMAIL}
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: "America/New_York"
      AIRFLOW__CORE__FERNET_KEY: "TrpFV5M4TmpWi4UxLXH90Trv_LttJL8S-_TcTZGus7U="
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    volumes:
      - ./airflow-home/dags:/opt/airflow/dags
      - ./airflow-home/logs:/opt/airflow/logs
      - ./airflow-home/config:/opt/airflow/config
      - ./airflow-home/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /bin/bash /entrypoint.sh
    ports:
      - "8080:8080"
    mem_limit:  2g
    cpus: '1.0'
    restart: unless-stopped
    depends_on:
        db-setup:
          condition: service_completed_successfully
    networks:
      - finance-network

  # Database Preparation
  db-setup:
    container_name: lambda-db-setup-ctr
    build:
      context: .
      dockerfile: docker/db-setup/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: python /app/db-init.py
    restart: "no"
    networks:
      - finance-network

  # CSV Processor Application
  csv-batch:
    container_name: lambda-csv-batch-ctr
    build:
      context: .
      dockerfile: docker/csv-batch/Dockerfile
    image: csv-batch:latest
    depends_on:
      postgres:
        condition: service_healthy
      db-setup:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    mem_limit: 1g
    cpus: 1.0
    volumes:
      - ./batch-datasource:/app/batch-datasource
      - ./airflow-home/csv_logs:/app/airflow-logs
    networks:
      - finance-network

  # Producer API
  producer:
    env_file:
      .env
    container_name: lambda-producer-ctr
    build:
      context: .
      dockerfile: docker/producer-stream/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      db-setup:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    mem_limit: 3g
    cpus: 2.0
    volumes:
      - ./airflow-home/producer_logs:/app/airflow-logs
    networks:
      - finance-network
    healthcheck:
      test: "pgrep -f producer.py || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: python producer.py

  ## Consumer
  consumer:
    env_file:
      .env
    container_name: lambda-consumer-ctr
    build:
      context: .
      dockerfile: docker/consumer-stream/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    mem_limit: 2g
    cpus: 4.0
    networks:
      - finance-network
    healthcheck:
      test: "pgrep -f consumer.py || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: python consumer.py

  kafka:
    container_name: lambda-kafka-ctr
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      CLUSTER_ID: kafka-cluster-1
    ports:
      - "9092:9092"
    mem_limit: 2g
    cpus: 4.0
    volumes:
      - fraud-detection-kafka:/var/lib/kafka/batch-datasource
      - /home/xxanonymousxx/kafka/config/server.properties:/kafka/config/server.properties
    networks:
      - finance-network
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


# Named volumes for batch-datasource persistence
volumes:
  fraud-detection-postgres:
  fraud-detection-kafka:

# Custom network for container communication
networks:
  finance-network:
    driver: bridge
