services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      DB_HOST: postgres
      POSTGRES_DB: finance
      POSTGRES_USER: dataeng
      POSTGRES_PASSWORD: secure123
    ports:
      - "5432:5432"
    volumes:
      - fraud_detection_postgres:/var/lib/postgresql/data

    networks:
      - finance_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataeng -d finance"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Pgadmin
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - finance_network

  # CSV Processor Application
  csv_processor:
    build:
      context: .
      dockerfile: batch_processor/batch_csv.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    networks:
      - finance_network

    command: python batch_processor/processor.py

  ## API
  producer_api:
    build:
      context: .
      dockerfile: producer_streaming_api/producer.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - finance_network
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: python producer_streaming_api/producer_api.py

  ## Consumer
  consumer_api:
    build:
      context: .
      dockerfile: consumer_stream_api/consumer.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: finance
      DB_USER: dataeng
      DB_PASSWORD: secure123
    ports:
      - "8001:8000"
    networks:
      - finance_network
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: python consumer_stream_api/consumer_api.py


  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - finance_network
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 5


# Named volumes for data persistence
volumes:
  fraud_detection_postgres:
  fraud_detection_kafka:

# Custom network for container communication
networks:
  finance_network:
    driver: bridge