services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: finance_db
    environment:
      DB_HOST: postgres
      POSTGRES_DB: finance
      POSTGRES_USER: dataeng
      POSTGRES_PASSWORD: secure123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - finance_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataeng -d finance"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CSV Processor Application
  csv_processor:
    build:
      context: .
      dockerfile: batch_processor/batch_csv.Dockerfile
    container_name: csv_batch_processor_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: finance
      DB_USER: dataeng
      DB_PASSWORD: secure123
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    networks:
      - finance_network
    command: python processor.py
## API
#  api:
#    build:
#      context: .
#      dockerfile: services/api/api.Dockerfile
#    container_name: api_app
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_NAME: ecommerce
#      DB_USER: dataeng
#      DB_PASSWORD: secure123
#    ports:
#      - "8000:8000"
#    networks:
#      - ecommerce_network
#    command: uvicorn api:app --host 0.0.0.0 --port 8000



# Named volumes for data persistence
volumes:
  postgres_data:

# Custom network for container communication
networks:
  finance_network:
    driver: bridge