
services:
  # PostgreSQL Database
  postgres:
    container_name: lambda-postgres-ctr
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    mem_limit: 2g
    cpus: 1.0
    volumes:
      - fraud_detection_postgres:/var/lib/postgresql/data

    networks:
      - finance_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataeng -d finance"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Pgadmin
  pgadmin:
    container_name: lambda-pgadmin-ctr
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    mem_limit: 512m
    cpus: .25
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - finance_network

# Database Preparation
  db-setup:
    container_name: lambda-db-setup-ctr
    build:
      context: .
      dockerfile: docker/db-setup/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env  # Make sure this line exists
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: python /app/db-init.py
    restart: "no"
    networks:
      - finance_network

  # CSV Processor Application
  csv-batch:
    container_name: lambda-csv-batch-ctr
    build:
      context: .
      dockerfile: docker/csv-batch/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      db-setup:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    env_file: .env  # Make sure this line exists
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    mem_limit: 1g
    cpus: 1.0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - finance_network
    command: sleep infinity

  # Cron Job Runner
  cron-runner:
    container_name: lambda-cron-runner-ctr
    env_file:
      .env
    build:
      context: .
      dockerfile: docker/cron/Dockerfile
    mem_limit: 1g
    cpus: .25
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - finance_network

  # Producer API
  producer:
    env_file:
      .env
    container_name: lambda-producer-ctr
    build:
      context: .
      dockerfile: docker/producer-stream/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      db-setup:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    mem_limit: 3g
    cpus: 2.0
    volumes:
      - ./logs:/app/logs
    networks:
      - finance_network
    healthcheck:
      test: "pgrep -f producer.py || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: python producer.py

  ## Consumer
  consumer:
    env_file:
      .env
    container_name: lambda-consumer-ctr
    build:
      context: .
      dockerfile: docker/consumer-stream/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    mem_limit: 2g
    cpus: 4.0
    networks:
      - finance_network
    healthcheck:
      test: "pgrep -f consumer.py || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: python consumer.py

  kafka:
    container_name: lambda-kafka-ctr
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      CLUSTER_ID: kafka-cluster-1
    ports:
      - "9092:9092"
    mem_limit: 2g
    cpus: 4.0
    volumes:
      - fraud_detection_kafka:/var/lib/kafka/data
    networks:
      - finance_network
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


# Named volumes for data persistence
volumes:
  fraud_detection_postgres:
  fraud_detection_kafka:

# Custom network for container communication
networks:
  finance_network:
    driver: bridge
