apiVersion: v1
kind: Namespace
metadata:
  name: namespace-dev
  labels:
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-prod
  labels:
    environment: production