apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-cron-runner
  namespace: dev
  labels:
    app: lambda
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lambda
  template:
    metadata:
      labels:
        app: lambda
    spec:
      containers:
        - name:	lambda-cron-runner-ctr
          image: 05261977/lambda-inspired-platform-cron-runner:latest