apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-kafka
  labels:
    app: lambda
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lambda
  template:
    metadata:
      labels:
        app: lambda
    spec:
      containers:
        - name:	lambda-kafka-ctr
          image:	confluentinc/cp-kafka:latest
          ports:
          - containerPort: 5050