    apiVersion: v1
    kind: Service
    metadata:
      name: lambda-postres
    spec:
      selector:
        app: lamda-postgres
      ports:
        - protocol: TCP
          port: 9092
          targetPort: 9092
      type: ClusterIP