    apiVersion: v1
    kind: Service
    metadata:
      name: lambda-postres
    spec:
      selector:
        app: lamda-postgres
      ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
      type: ClusterIP