    apiVersion: v1
    kind: Service
    metadata:
      name: lambda-postgres
    spec:
      selector:
        app: lambda-postgres
      ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
      type: ClusterIP